// <auto-generated />
namespace CSA_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Registration_page : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registration_page));
        
        string IMigrationMetadata.Id
        {
            get { return "201805200846117_Registration_page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
